### ISSUE TITLE
Getting an exception DllNotFound

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-visualstudio#150]
**Actual behavior**
Getting an exception while trying to execute the tests on VS.

**Steps to replicate**
With the latest Gauge from the build pipeline, I am able to add the project. 
I set the use execution API flag - on VS 2015
When I am running the tests from the test explorer getting the following error
```
Discover Scenarios started. Using : ProjectRoot: Z:\Documents\Visual Studio 2015\Projects\GaugeProject5\GaugeProject5, OutputPath: Z:\Documents\Visual Studio 2015\Projects\GaugeProject5\GaugeProject5\bin\Debug\, API Port: 1000, API V2 Port: 2000
Adding test cases from : Z:\Documents\Visual Studio 2015\Projects\GaugeProject5\GaugeProject5\specs\example.spec
Discovered scenario: Vowel counts in single word
Discovered scenario: Vowel counts in multiple word
UseExecutionAPI=true, executing specs via Gauge API.
Vowel counts in multiple word scenario
Vowel counts in single word scenario
System.DllNotFoundException: Unable to load DLL 'grpc_csharp_ext.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Grpc.Core.Internal.GrpcLog.grpcsharp_redirect_log(GprLogDelegate callback)
   at Grpc.Core.Internal.GrpcLog.RedirectNativeLogs(TextWriter textWriter)
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.Initialize()
   at Gauge.VisualStudio.TestAdapter.GaugeRunnerV2.<Run>d__14.MoveNext()
========== Run test finished: 0 run (0:00:00.6479991) ==========
```
**Version**
```
Gauge version: 0.6.3

Plugins
-------
csharp (0.9.3.nightly-2016-11-04)
html-report (2.2.0.nightly-2016-11-29)
java (0.5.1.nightly-2016-08-18)
ruby (0.3.2.nightly-2016-08-22)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by sriv** [comment]
Closing this, since use of grpc is ditched.
