### ISSUE TITLE
Gauge-Error Occurred Unable to launch Gauge Daemon.

### ISSUE THREAD

**Issue by mura28info** [getgauge/gauge-visualstudio#200]
### Expected behavior
Gauge project should open properly when we open Visual Studio.

### Actual behavior
It throws exception message box that Gauge-Error Occurred Unable to launch Gauge Daemon. Check Output Window for details. In output window below error messages are observed.
------ Load Playlist started ------
========== Load Playlist finished (0:00:00) ==========
Object reference not set to an instance of an object.
------ Discover test started ------
========== Discover test finished: 0 found (0:00:01.6741674) ==========

### Steps to reproduce
1. Install Gauge Visual studio 2015 extension.
2.Add a project and work with it.

### Version Information
Visual Studio 2015 Community Edition
VisualStudio Version and Edition  :-
Gauge VisualStudio Plugin Version :-
Gauge version: 0.9.2
Commit Hash: e2c0d17

Plugins
-------
csharp (0.10.1)
html-report (4.0.2)
```
Run gauge -v on your system and paste the results here.
```

**Comment by Apoorva-GA** [comment]
@mura28info I am on the same version of yours and everything seems to work fine for me.
Could you give us some more info like the stack trace and can you also look at the logs directory in the project root and check `api.log` and `gauge.log` to check if we can get any additional information.

**Comment by mura28info** [comment]
Hi Apoorva,
Sorry for the delayed response, Still I am facing the same problem. PFA for the trace logs.

Let me know if you need any more information.

[ActivityLog.txt](https://github.com/getgauge/gauge-visualstudio/files/1299483/ActivityLog.txt)

**Comment by mura28info** [comment]
gauge.log, displays "Unable to create Sandbox in D:\C sharp\Gauge\GaugeSample\GaugeSample\bin\Debug\" message.

**Comment by mura28info** [comment]
api.log file is not generated in my project.

**Comment by mura28info** [comment]
Adding output as well fromVS2015:

Output Window logs from Gauge
[Debug] Opening Gauge Daemon for Project : GaugeProject1, at ports: 1000, 2000
[Debug] Opening Gauge Daemon with PID: 13284
[Error] Failed to start Gauge Daemon: System.Exception: Could not connect ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:1000
at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
at Gauge.CSharp.Core.TcpClientWrapper..ctor(Int32 port)
--- End of inner exception stack trace ---
at Gauge.CSharp.Core.TcpClientWrapper..ctor(Int32 port)
at Gauge.VisualStudio.Core.GaugeService.StartGaugeAsDaemon(Project gaugeProject)
Output window logs from Tests
------ Load Playlist started ------
========== Load Playlist finished (0:00:00.003) ==========
The given key was not present in the dictionary.
------ Discover test started ------
========== Discover test finished: 0 found (0:00:01.954) ==========

**Comment by sguptatw** [comment]
Able to replicate the issue with the released version of Gauge.
Observation - With the latest nightly this issue does not occur.

**Comment by mura28info** [comment]
@sguptatw thanks for the reply, the latest c# code if download and compile we should not see this issue right?...Is any update planned for c# plugin from your side?

**Comment by nehashri** [comment]
@mura28info The issue seems to be with gauge and not visual studio plugin. You can find the latest nightly release of gauge [here](https://bintray.com/gauge/Gauge/Nightly).

**Comment by mura28info** [comment]
@nehashri My bad, that I have tried only with VS build, now I have updated gauge nightly build as well but still, I am facing the same issue. 
Attached Logs for this.
[ActivityLog.txt](https://github.com/getgauge/gauge-visualstudio/files/1309970/ActivityLog.txt)

**Version Informations:**
Gauge version: 0.9.3.nightly-2017-09-15
Commit Hash: dd2faa7
**Plugins
-------**
csharp (0.10.1)
html-report (4.0.2)
ruby (0.4.2)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)

**Comment by mura28info** [comment]
Hi All,
This issue is not observed on last nightly build, **"0.9.3.nightly-2017-09-18"** I will monitor this for today, if the issue is not reproduced, I will close this ticket.

Thanks For the support team.

**Comment by mura28info** [comment]
Intermittently I am observing this issue still.

**Comment by itsmemittal** [comment]
Hi All, 
I observe this issue at my end if i have specs are in larger quantity arround 1000 then i got this issue.

**Comment by mura28info** [comment]
@itsmemittal I am getting with 10 line spec itself :( you are getting with small spec files? if yes can you please which version you are using it?

**Comment by nehashri** [comment]
@mura28info A temporary fix for this could be to allow gauge to run as a trusted app in windows. The settings can be changed in Control Panel > System and Security > Windows Firewall > Allowed apps. `gauge` app should be given private and public access. Could you try this and let us know?

**Comment by mura28info** [comment]
@nehashri Currently my firewall is blocked by admin...Will update you by tomorrow. Thanks for the info
