### ISSUE TITLE
VS Crashes with NPE

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge-visualstudio#28]
Stack Trace

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
Stack:
   at Gauge.VisualStudio.GaugeDTEProvider.GetApiConnectionForActiveDocument()
   at Gauge.VisualStudio.Models.Concept.GetAllConcepts()
   at Gauge.VisualStudio.SpecsChangeWatcher.WatcherOnChanged(System.Object, System.IO.FileSystemEventArgs)
   at System.IO.FileSystemWatcher.OnChanged(System.IO.FileSystemEventArgs)
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(Int32, System.String)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
```

Root Cause:

There is a FileSystemWatcher watching changes to specs/concepts, which refreshes the Concept and Step cache on change. The `Concept.Refresh` and `Step.Refresh` both seek a handle to GaugeAPIConnection for the project that contains the ActiveDocument. This is bad, since the files can change outside Visual Studio. Temporarily, disabled this feature.

**Comment by sriv** [comment]
Removed the FileSystemWatcher. VS Plugin does not cache Concept and Step list anymore, it is cheap and easy to just fetch it from Gauge.
